javac -encoding UTF8 commons/DbMySql.java
javac -encoding UTF8 commons/Meniu.java
javac -encoding UTF8 crud/CrudXY.java
javac -encoding UTF8 crud/CrudXYPlanai.java
javac -encoding UTF8 klientai/Kliento_krit.java
javac -encoding UTF8 planai/PlanoPratimas.java
javac -encoding UTF8 pratimai/Pratimai.java
javac -encoding UTF8 raumenys/raumenys.java
javac -encoding UTF8 enum/treniruociu_rusis.java